name = input("Please Enter Your Name:" "\n")
labGrade = input("Please Write Your Lab Grade""\n")
midtermGrade = input("Please Write Your Midterm Grade""\n")
finalGrade = input("Please Write Your Final Grade""\n")
lastScore = (int(labGrade) * 25 / 100) + (int(midtermGrade) * 35 / 100) + (int(finalGrade) * 40 / 100)
print("Name:", name, "\n")
print("Lab:", int(labGrade),  "\n")
print("Midterm:", int(midtermGrade),  "\n")
print("Final:", int(finalGrade),  "\n")
print("Last Score:", float(lastScore),  "\n")
